version: '3'
services:
  api:
    build: ./api
    ports:
      - "8000:8000"
  orchestrator:
    build: ./orchestrator
  runner:
    build: ./runner
  inference:
    build: ./inference
    ports:
      - "8003:8003"
